# Generated by Django 3.0.4 on 2020-05-10 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
        ('blog', '0004_auto_20200501_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='siteapp.Site'),
            preserve_default=False,
        ),
    ]
