# Generated by Django 3.1.4 on 2020-12-17 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
        ('blog', '0005_post_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.site'),
        ),
    ]
