# Generated by Django 3.2.6 on 2021-08-25 14:11

from django.db import migrations, models
from slugify import slugify


def set_slug_defaults(apps, schema_editor):
    post_model = apps.get_model('blog', 'post')
    for post in post_model.objects.all().iterator():
        post.slug = slugify(post.title)
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210824_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=512, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_slug_defaults),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=512, unique=True, null=False),
        ),
    ]
