# Generated by Django 3.2.6 on 2021-08-24 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=128)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
