# Generated by Django 3.2.6 on 2021-08-25 08:12

from django.db import migrations, models


def set_my_defaults(apps, schema_editor):
    tag_model = apps.get_model('siteapp', 'tag')
    for tag in tag_model.objects.all().iterator():
        tag.code = tag.tag.lower()
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_auto_20210824_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.RunPython(set_my_defaults),
        migrations.AlterField(
            model_name='tag',
            name='code',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
