# Generated by Django 3.2.6 on 2021-08-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_tag_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='code',
            new_name='slug',
        ),
    ]
