# Generated by Django 3.2.6 on 2021-08-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_site'),
        ('siteapp', '0004_rename_code_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='site',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
